### PR TITLE
Adapt qtox to new conferences state change callback.

### PR DESCRIPTION
**Pull request by iphydf**
See https://github.com/TokTok/c-toxcore/pull/295.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/qtox/7)

### CODE REVIEW

**Comment by tox-user** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/qtox/7#-:-L4ZM5S7s-Wm8hk_6ySW:b-jbsf8z)*

**Comment by tox-user** [comment]
Persistent group chats require more testing. It doesn't crash on restart anymore with this code, but crashes still happen. 

One way to cause a crash:
Alice creates a group and invites Bob. Bob joins. Alice restarts her client. Bob will most likely crash after Alice rejoins. This will only happen if Alice reconnects quickly enough for Bob to not notice she ever went offline.

When you are in group chat and close qTox the log usually says "Illegal instruction" or "Segmentation fault" on quit. It happened to me once that two conferences were created instead of one on both clients. I never managed to repeat it, but once second group was created on one client, when the second client reconnected. Another problem is that when you reconnect to a persistent group, you don't see the correct group title anymore, unless it changes.

**Comment by iphydf** [comment]
@tox-user can you help me reproduce this and/or run qtox in gdb and give me a backtrace.

**Comment by tox-user** [comment]
This time I had to try a few more times to make it happen. Backtrace and a part of the log:
```
core/core.cpp:505 : Debug: "AV group invite by 4294967295"
audio/backend/openal.cpp:300 : Debug: Opening audio input "Built-in Audio Analog Stereo"
[New Thread 0x7fff8f7fe700 (LWP 3562)]
audio/backend/openal.cpp:324 : Debug: Opened audio input "Built-in Audio Analog Stereo"
audio/backend/openal.cpp:246 : Debug: Subscribed to audio input device [ 1 subscriptions ]
core/core.cpp:537 : Debug: "Group namelist change 0:0 0"

Thread 1 "qtox" received signal SIGSEGV, Segmentation fault.
0x00007ffff79aceb0 in QLabel::text() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff79aceb0 in QLabel::text() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x0000555555872134 in GroupChatForm::updateUserNames() ()
#2  0x0000555555871814 in GroupChatForm::onUserListChanged() ()
#3  0x00005555558774cb in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (GroupChatForm::*)()>::call(void (GroupChatForm::*)(), GroupChatForm*, void**) ()
#4  0x0000555555876ef8 in void QtPrivate::FunctionPointer<void (GroupChatForm::*)()>::call<QtPrivate::List<>, void>(void (GroupChatForm::*)(), GroupChatForm*, void**) ()
#5  0x00005555558764f9 in QtPrivate::QSlotObject<void (GroupChatForm::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#6  0x00007ffff05dc95e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00005555557a37bb in Group::userListChanged(unsigned int, QMap<QByteArray, QString> const&) ()
#8  0x000055555580d74a in Group::regeneratePeerList() ()
#9  0x0000555555781346 in Widget::onGroupNamelistChanged(int, int, unsigned char) ()
#10 0x00005555557235e9 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2>, QtPrivate::List<int, int, unsigned char>, void, void (Widget::*)(int, int, unsigned char)>::call(void (Widget::*)(int, int, unsigned char), Widget*, void**) ()
#11 0x0000555555722808 in void QtPrivate::FunctionPointer<void (Widget::*)(int, int, unsigned char)>::call<QtPrivate::List<int, int, unsigned char>, void>(void (Widget::*)(int, int, unsigned char), Widget*, void**) ()
#12 0x00005555557218b5 in QtPrivate::QSlotObject<void (Widget::*)(int, int, unsigned char), QtPrivate::List<int, int, unsigned char>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#13 0x00007ffff05dd499 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff78c146b in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff79c092b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x0000555555782168 in Widget::event(QEvent*) ()
#17 0x00007ffff7879b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff7881341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff05b09e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff05b316d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff0604c43 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff2ce07f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff2ce0a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff2ce0b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff060504f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff05ae9ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff05b713c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x000055555570f2a1 in main ()
```

**Comment by tox-user** [comment]
Here is the one for segmentation fault on exit:
```
main.cpp:65 : Debug: Cleanup success
[Thread 0x7fffcaac4700 (LWP 3790) exited]
main.cpp:361 : Debug: Exit with status 0
[Thread 0x7fffd14fc700 (LWP 3789) exited]
[Thread 0x7fff9ffff700 (LWP 3800) exited]
[Thread 0x7fffa4bde700 (LWP 3799) exited]
[Thread 0x7fffa53df700 (LWP 3798) exited]
[Thread 0x7fffc9231700 (LWP 3792) exited]
audio/backend/openal.cpp:467 : Debug: Closing audio input
[Thread 0x7fff8ebdd700 (LWP 3810) exited]
[Thread 0x7fffc9a32700 (LWP 3791) exited]

Thread 1 "qtox" received signal SIGSEGV, Segmentation fault.
0x00007ffff07f1880 in QObject::staticMetaObject () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff07f1880 in QObject::staticMetaObject () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x0000555555802100 in ToxGroupCall::~ToxGroupCall() ()
#2  0x00005555557f3659 in std::pair<int const, ToxGroupCall>::~pair() ()
#3  0x00005555557f369b in void __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, ToxGroupCall> > >::destroy<std::pair<int const, ToxGroupCall> >(std::pair<int const, ToxGroupCall>*) ()
#4  0x00005555557f2c5f in void std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<int const, ToxGroupCall> > > >::destroy<std::pair<int const, ToxGroupCall> >(std::allocator<std::_Rb_tree_node<std::pair<int const, ToxGroupCall> > >&, std::pair<int const, ToxGroupCall>*) ()
#5  0x00005555557f1f38 in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::_M_destroy_node(std::_Rb_tree_node<std::pair<int const, ToxGroupCall> >*)
    ()
#6  0x00005555557f0202 in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::_M_drop_node(std::_Rb_tree_node<std::pair<int const, ToxGroupCall> >*) ()
#7  0x00005555557eef3f in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::_M_erase(std::_Rb_tree_node<std::pair<int const, ToxGroupCall> >*) ()
#8  0x00005555557ed72d in std::_Rb_tree<int, std::pair<int const, ToxGroupCall>, std::_Select1st<std::pair<int const, ToxGroupCall> >, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::~_Rb_tree() ()
#9  0x00005555557f4703 in std::map<int, ToxGroupCall, std::less<int>, std::allocator<std::pair<int const, ToxGroupCall> > >::~map() ()
#10 0x00007fffef810910 in __run_exit_handlers (status=0, listp=0x7fffefb745d8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at exit.c:83
#11 0x00007fffef81096a in __GI_exit (status=<optimized out>) at exit.c:105
#12 0x00007fffef7fb2b8 in __libc_start_main (main=0x55555570d82a <main>, argc=3, argv=0x7fffffffe1b8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe1a8) at ../csu/libc-start.c:325
#13 0x000055555570c87a in _start ()
```

**Pull request merged**
