### PR TITLE
refactor: Rename Group Chat to Conference

### PR DESCRIPTION
**Pull request by Pigpog**
Conference is the correct name per Tox protocol. Now that Tox has implemented new group chats, it is important to refer to conferences properly.

I have also changed tokens that were named "g", short for "group", to "c".

Solves #67.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/qTox/92)

### CODE REVIEW

**Review by iphydf — APPROVED** [review]

**Comment by Pigpog** [comment]
I'll work on this more later today. 

I think I'd probably change "standing together in a conference" back to "group", and then do a more general revision of the user manual in another pull request. I noticed the writing could use work, and this way we stay in the scope of this PR.

**Comment by iphydf** [comment]
Sounds good, let's merge it and make a separate pr for more revision.

**Comment by Pigpog** [comment]
Looking at the CI failures, i'm not sure what I can do. Some simply timed out, and the `restyled` one had an error due to the length of the diff. 
For "build test and deploy", test_notificationgenerator failed and i'm not sure why. It seems like it is probably related to my changes. 
I'll come back to this tomorrow.

**Comment by iphydf** [comment]
To fix the restyled issue, run clang-format (version 18) on the code: `clang-format-18 -i $(find src -name "*.h" -or -name "*.cpp")`

**Comment by iphydf** [comment]
```sh
docker run \
  -u "$(id -u):$(id -g)" \
  --rm \
  -v "$PWD:/code" \
  -it \
  restyled/restyler-clang-format:5f451c6f0eaf66f7358cea647af09c3df27b76fd \
  clang-format -i $(find src -name "*.h" -or -name "*.cpp")
```

**Comment by iphydf** [comment]
I've fixed your test.

**Review by Green-Sky — APPROVED** [review]

**Pull request merged**
